# Generated by Django 6.0.3 on 2026-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file from your computer.', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file from your computer.', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste a full https:// URL to an image hosted online.'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste a full https:// URL.'),
        ),
    ]
