# Generated by Django 6.0.3 on 2026-03-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_image_productimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_delivery_label', models.CharField(default='3–5 business days across Nepal', help_text='e.g. "3–5 business days across Nepal"', max_length=100)),
                ('standard_free_above', models.DecimalField(decimal_places=2, default=2000, help_text='Orders above this amount qualify for free standard delivery (NPR).', max_digits=10)),
                ('express_delivery_label', models.CharField(default='Next-day delivery within Kathmandu Valley', help_text='e.g. "Next-day delivery within Kathmandu Valley"', max_length=100)),
                ('express_surcharge', models.DecimalField(decimal_places=2, default=150, help_text='Extra fee charged for express delivery (NPR).', max_digits=8)),
                ('stock_note', models.CharField(blank=True, help_text='Optional custom note shown under "Available In Stock". Leave blank to auto-show the product\'s actual stock count.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Settings',
                'verbose_name_plural': 'Delivery Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, help_text='City / District (required for home delivery)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('home', 'Home Delivery'), ('pickup', 'Pickup')], default='home', help_text='Home Delivery or Pickup', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, choices=[('koshi', 'Koshi Province'), ('madhesh', 'Madhesh Province'), ('bagmati', 'Bagmati Province'), ('gandaki', 'Gandaki Province'), ('lumbini', 'Lumbini Province'), ('karnali', 'Karnali Province'), ('sudurpashchim', 'Sudurpashchim Province')], help_text='Province (required for home delivery)', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(blank=True, help_text='Tole, Ward No., Landmark', max_length=255),
        ),
    ]
