# Generated by Django 6.0.3 on 2026-03-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_deliverysettings_order_city_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverysettings',
            name='express_delivery_label',
        ),
        migrations.RemoveField(
            model_name='deliverysettings',
            name='standard_delivery_label',
        ),
        migrations.RemoveField(
            model_name='deliverysettings',
            name='stock_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='province',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address',
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='express_badge_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='express_description',
            field=models.CharField(default='Next-day delivery within Kathmandu Valley', max_length=200),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='express_label',
            field=models.CharField(default='Express Delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='pickup_address',
            field=models.CharField(blank=True, default='New Road, Kathmandu', max_length=300),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='pickup_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='pickup_hours',
            field=models.CharField(blank=True, default='Sun–Fri, 10 AM – 6 PM', max_length=200),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='standard_badge_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='standard_description',
            field=models.CharField(default='3–5 business days across Nepal', max_length=200),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='standard_label',
            field=models.CharField(default='Standard Delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='delivery_type',
            field=models.CharField(choices=[('home', 'Home Delivery'), ('pickup', 'Pickup')], default='home', max_length=10),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='province',
            field=models.CharField(blank=True, choices=[('koshi', 'Koshi Province'), ('madhesh', 'Madhesh Province'), ('bagmati', 'Bagmati Province'), ('gandaki', 'Gandaki Province'), ('lumbini', 'Lumbini Province'), ('karnali', 'Karnali Province'), ('sudurpashchim', 'Sudurpashchim Province')], max_length=20),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='street_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='express_surcharge',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=8),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='standard_free_above',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingsetting',
            name='free_above',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxsetting',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
